---

# Ansible role to install Oracle Java 12

  - name: Check If java is already installed or not
    shell: "{{ java_name }}/bin/java -version 2>&1 | grep version | awk '{print $3}' | sed 's/\"//g'"
    register: java_installed
    
  - name:  java version
    debug:
      var: java_installed 
  
  - name: Installed java version
    debug:
      var: java_installed.stdout 

  - block:  
    - name: Download Java
      get_url:
        url: "{{ download_url }}"
        dest: "{{ java_package }}"
        headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie; --no-check-certificate'     

    - yum:
        name: "{{ java_package }}"
        state: installed

    - name: Set/Configure JAVA_HOME in environment variables 
      shell: "echo 'export JAVA_HOME={{java_name}}\n export PATH=$JAVA_HOME/bin:$PATH' > {{java_env_file}}"
    
    - name: Exports/Run java env file for make JAVA_HOME available globally
      shell: "source {{java_env_file}}"

    - name: Clean up
      file: state=absent path="{{ java_package }}"
    
    when: java_installed.stdout == ""
